[package]
name = "web-memory"
version = "0.1.0"
authors = ["taroosg <root@taroosg.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
